---
- name: Check for json and upload to GCP Bucket
  hosts: workload-generators
  vars:
    directory_to_search: "wg/http"
    gcp_bucket_path: "gs:bucket"

  tasks:
    - name: Search for .json files in given directory
      find:
        paths: "{{ directory_to_search }}"
        patterns: "results.json"
        recurse: no
      register: res

    - name: Fail if no res.json file exists
      fail:
        msg: "No result files found in the given directory"
      when: res.matched == 0

    - name: Upload .ycsb_txt file to GCP bucket using gsutil
      command: gsutil cp "{{ item.path }}" "{{ gcp_bucket_path }}"
      with_items: "{{ res.files }}"
      when: res.matched > 0
