on:
  workflow_call:
jobs:
  CI-infra-changes:
    name: CI-infra-changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install python-hcl2 

    - name: cat input.tfvars before update
      run: | 
        cat ./bench/terraform/input.tfvars

    - name: Run Terraform Update Script
      run: |
          python ./scripts/infra_change_detector.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action

    - name: Cancel workflow if no changes detected
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: exit 1

    - name: cat input.tfvars after update
      run: |
        cat ./bench/terraform/input.tfvars

  CI-send-infra-info:
    name: CI - push infra changes to bench3
    needs: [CI-infra-changes]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: cat input.tfvars
      run: |
        cat ./bench/terraform/input.tfvars

    - name: Install Dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install python-hcl2 

    - name: Run Terraform Update Script
      run: |
        python ./scripts/fetch_instance_type_from_tfvars.py

    - name: cat ./scripts/infra.txt
      run: |
        cat ./scripts/infra.txt

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN_TO_PUSH_TO_BENCH }}
      with:
        source-directory: './scripts'
        destination-github-username: 'DawidNiezgodka'
        destination-repository-name: 'tinyFaaS-bench'
        target-directory: './machine_type'
        target-branch: main
